/**
 * storageService.ts
 * Handles file uploads to Supabase Storage (radiology bucket).
 * Images are stored as files, not base64 strings in the database.
 *
 * Security: the radiology bucket should be set to PRIVATE in Supabase Dashboard
 * (Storage → radiology → Edit → uncheck "Public"). All image access goes through
 * signed URLs generated by resolveImageUrl(), which expire after 1 hour.
 * The storage path (not the full URL) is persisted in imaging.image_url.
 */

import { supabase } from '../lib/supabase';
import { generateId } from '../utils/sanitize';

// Allowed image MIME types, plus PDF for scanned/exported reports (e.g. culture
// reports) — anything else is rejected before upload
const ALLOWED_MIME_TYPES = new Set([
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/gif',
  'image/heic',
  'image/heif',
  'application/pdf',
]);

const MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024; // 10 MB pre-compression limit
const MAX_DIMENSION_PX    = 1920;              // max width or height after resize
const JPEG_QUALITY        = 0.82;             // JPEG quality for compressed output
const SIGNED_URL_TTL_S    = 3600;             // 1-hour signed URL TTL
const SIGNED_URL_REFRESH  = 50 * 60 * 1000;  // refresh after 50 min (10 min before expiry)

// ─── In-memory signed URL cache ───────────────────────────────────────────────
interface CachedUrl { signedUrl: string; expiresAt: number }
const _urlCache = new Map<string, CachedUrl>();

/** Validate MIME type against allowlist. Throws with user-friendly message on failure. */
export function validateImageFile(file: File): void {
  if (!ALLOWED_MIME_TYPES.has(file.type)) {
    throw new Error(`Unsupported file type "${file.type}". Please upload a JPEG, PNG, WebP image, or PDF.`);
  }
  if (file.size > MAX_FILE_SIZE_BYTES) {
    throw new Error(`File too large (${(file.size / 1024 / 1024).toFixed(1)} MB). Maximum is 10 MB.`);
  }
}

/** Is the stored path/URL a PDF? Used to render a file icon instead of an image tag. */
export function isPdfPath(pathOrUrl: string): boolean {
  return pathOrUrl.toLowerCase().endsWith('.pdf');
}

/**
 * Compress an image file using the Canvas API.
 * Resizes to MAX_DIMENSION_PX on the longest side and re-encodes as JPEG.
 * Falls back to original file if canvas is unavailable (SSR / test environments).
 */
async function compressImage(file: File): Promise<File> {
  if (file.type === 'image/gif' || file.type === 'application/pdf') return file;

  return new Promise<File>((resolve) => {
    const img = new Image();
    const objectUrl = URL.createObjectURL(file);

    img.onload = () => {
      URL.revokeObjectURL(objectUrl);
      try {
        let { width, height } = img;
        if (width > MAX_DIMENSION_PX || height > MAX_DIMENSION_PX) {
          if (width >= height) {
            height = Math.round((height / width) * MAX_DIMENSION_PX);
            width  = MAX_DIMENSION_PX;
          } else {
            width  = Math.round((width / height) * MAX_DIMENSION_PX);
            height = MAX_DIMENSION_PX;
          }
        }

        const canvas = document.createElement('canvas');
        canvas.width  = width;
        canvas.height = height;
        const ctx = canvas.getContext('2d');
        if (!ctx) { resolve(file); return; }

        ctx.drawImage(img, 0, 0, width, height);
        canvas.toBlob(
          (blob) => {
            if (!blob) { resolve(file); return; }
            const compressed = new File([blob], file.name, { type: 'image/jpeg', lastModified: Date.now() });
            resolve(compressed.size < file.size ? compressed : file);
          },
          'image/jpeg',
          JPEG_QUALITY,
        );
      } catch {
        resolve(file);
      }
    };

    img.onerror = () => {
      URL.revokeObjectURL(objectUrl);
      resolve(file);
    };

    img.src = objectUrl;
  });
}

/**
 * Extract the storage path from either a stored path or a legacy full public URL.
 * New uploads store a bare path (e.g. "hospitalId/patientId/uuid.jpg").
 * Legacy rows may store a full URL ("https://xyz.supabase.co/.../radiology/hospitalId/...").
 */
export function extractStoragePath(urlOrPath: string): string {
  if (!urlOrPath.startsWith('http')) return urlOrPath; // already a path
  try {
    const url = new URL(urlOrPath);
    const marker = '/radiology/';
    const idx = url.pathname.indexOf(marker);
    if (idx === -1) return urlOrPath;
    return decodeURIComponent(url.pathname.slice(idx + marker.length));
  } catch {
    return urlOrPath;
  }
}

/**
 * Resolve a storage path or legacy URL to a short-lived signed URL.
 * Returns null for data: URIs (legacy base64), empty strings, or on error.
 * Results are cached for 50 minutes so repeated renders don't hammer the API.
 */
export async function resolveImageUrl(pathOrUrl: string): Promise<string | null> {
  if (!pathOrUrl || pathOrUrl.startsWith('data:')) return pathOrUrl || null;

  const path = extractStoragePath(pathOrUrl);

  const cached = _urlCache.get(path);
  if (cached && cached.expiresAt > Date.now()) return cached.signedUrl;

  const { data, error } = await supabase.storage
    .from('radiology')
    .createSignedUrl(path, SIGNED_URL_TTL_S);

  if (error || !data?.signedUrl) return null;

  _urlCache.set(path, { signedUrl: data.signedUrl, expiresAt: Date.now() + SIGNED_URL_REFRESH });
  return data.signedUrl;
}

/**
 * Upload an investigation image to Supabase Storage.
 * Returns the storage PATH (not a full URL) — callers must use resolveImageUrl()
 * to get a signed URL for display. This keeps PHI off of permanent public URLs.
 *
 * Bucket setup: Dashboard → Storage → radiology → set to PRIVATE.
 */
export async function uploadInvestigationImage(file: File, hospitalId: string, patientIpNo: string): Promise<string> {
  validateImageFile(file);

  const compressed = await compressImage(file);

  const ext = compressed.type === 'image/jpeg' ? 'jpg' : (file.name.split('.').pop()?.toLowerCase() || 'jpg');
  // Path: {hospitalId}/{patientIpNo}/{uuid}.{ext} — hospital_id prefix scopes storage to tenant
  const filePath = `${hospitalId}/${patientIpNo}/${generateId()}.${ext}`;

  const { error } = await supabase.storage
    .from('radiology')
    .upload(filePath, compressed, { contentType: compressed.type, upsert: false });

  if (error) throw new Error(`Image upload failed: ${error.message}`);

  // Return the path — not a public URL. Stored in imaging.image_url.
  return filePath;
}

/**
 * Evict a path from the signed-URL cache so the next resolveImageUrl call
 * generates a fresh signed URL. Used by the auto-refresh timer in useSignedUrl.
 */
export function clearImageUrlCache(pathOrUrl: string): void {
  const path = extractStoragePath(pathOrUrl);
  _urlCache.delete(path);
}

/**
 * Delete an investigation image from Supabase Storage.
 * Accepts both the new path format and legacy full URLs.
 * Gracefully skips data: URIs (legacy base64).
 */
export async function deleteInvestigationImage(imageUrl: string): Promise<void> {
  if (!imageUrl || imageUrl.startsWith('data:')) return;

  try {
    const filePath = extractStoragePath(imageUrl);
    const { error } = await supabase.storage.from('radiology').remove([filePath]);
    if (error) console.error('[Storage] Failed to delete image:', error.message);
    _urlCache.delete(filePath);
  } catch {
    // URL parsing failed — ignore
  }
}
