import jsPDF from 'jspdf';
import { Capacitor } from '@capacitor/core';

interface ScanForExport {
  type: string;
  region?: string;
  date: string;
  imageUrl: string;
  thumbnailUrl?: string;
  notes?: string;
}

interface PatientForExport {
  name: string;
  age: number;
  gender: string;
  ipNo: string;
  ward: string;
  diagnosis: string;
  dos?: string;
}

export async function exportRadiologyPDF(
  patient: PatientForExport,
  scans: ScanForExport[],
  phase: 'PreOp' | 'PostOp',
  onProgress?: (pct: number) => void,
): Promise<void> {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = 210, pageH = 297, margin = 15;
  let y = margin;

  // ── Header ──────────────────────────────────────────────────────────
  pdf.setFillColor(15, 23, 42);
  pdf.rect(0, 0, pageW, 28, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('MediWard', margin, 12);

  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(148, 163, 184);
  pdf.text('Clinical Radiology Report', margin, 20);

  const phaseRgb: [number, number, number] = phase === 'PreOp' ? [29, 78, 216] : [13, 148, 136];
  pdf.setFillColor(...phaseRgb);
  pdf.roundedRect(pageW - margin - 32, 8, 32, 10, 2, 2, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'bold');
  pdf.text(phase === 'PreOp' ? 'PRE-OP' : 'POST-OP', pageW - margin - 24, 14.5);

  y = 38;

  // ── Patient block ────────────────────────────────────────────────────
  pdf.setFillColor(241, 245, 249);
  pdf.roundedRect(margin, y, pageW - 2 * margin, 26, 3, 3, 'F');
  pdf.setTextColor(15, 23, 42);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(13);
  pdf.text(patient.name, margin + 4, y + 9);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);
  pdf.setTextColor(71, 85, 105);
  pdf.text(
    `${patient.age}y ${patient.gender}  ·  IP: ${patient.ipNo}  ·  ${patient.ward}  ·  ${patient.diagnosis}`,
    margin + 4, y + 17,
  );
  if (patient.dos) {
    pdf.text(
      `DOS: ${new Date(patient.dos).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`,
      margin + 4, y + 23,
    );
  }
  y += 34;

  // ── Phase heading ────────────────────────────────────────────────────
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...phaseRgb);
  pdf.text(
    `${phase === 'PreOp' ? 'Pre-Operative' : 'Post-Operative'} Radiology (${scans.length} image${scans.length !== 1 ? 's' : ''})`,
    margin, y,
  );
  y += 8;

  // ── Images (2-column grid) ───────────────────────────────────────────
  const imgW = (pageW - 2 * margin - 6) / 2;
  const imgH = 60;
  let col = 0;

  for (let i = 0; i < scans.length; i++) {
    onProgress?.(Math.round((i / scans.length) * 80));
    const scan = scans[i];
    const x = margin + col * (imgW + 6);

    pdf.setFillColor(248, 250, 252);
    pdf.setDrawColor(226, 232, 240);
    pdf.roundedRect(x, y, imgW, imgH + 20, 3, 3, 'FD');

    const imageUrl = scan.thumbnailUrl || scan.imageUrl;
    if (imageUrl) {
      try {
        const response = await fetch(imageUrl);
        const blob = await response.blob();
        const base64 = await new Promise<string>(resolve => {
          const reader = new FileReader();
          reader.onload = () => resolve((reader.result as string).split(',')[1]);
          reader.readAsDataURL(blob);
        });
        const ext = imageUrl.toLowerCase().includes('.png') ? 'PNG' : 'JPEG';
        pdf.addImage(`data:image/${ext.toLowerCase()};base64,${base64}`, ext, x + 1, y + 1, imgW - 2, imgH - 2);
      } catch {
        pdf.setFillColor(15, 23, 42);
        pdf.roundedRect(x + 1, y + 1, imgW - 2, imgH - 2, 2, 2, 'F');
        pdf.setTextColor(148, 163, 184);
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'bold');
        pdf.text(scan.type, x + imgW / 2, y + imgH / 2, { align: 'center' });
      }
    }

    const metaY = y + imgH + 3;
    pdf.setTextColor(15, 23, 42);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(8);
    pdf.text(scan.region || scan.type, x + 3, metaY + 5, { maxWidth: imgW - 6 });
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 116, 139);
    pdf.setFontSize(7);
    pdf.text(
      new Date(scan.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: '2-digit' }),
      x + 3, metaY + 12,
    );

    col++;
    if (col === 2) {
      col = 0;
      y += imgH + 24;
      if (y + imgH + 24 > pageH - margin) {
        pdf.addPage();
        y = margin;
      }
    }
  }

  // ── Footer ───────────────────────────────────────────────────────────
  const totalPages = pdf.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    pdf.setPage(p);
    pdf.setFontSize(7);
    pdf.setTextColor(148, 163, 184);
    pdf.text(
      `Generated by MediWard · ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`,
      margin, pageH - 8,
    );
    pdf.text(`Page ${p} of ${totalPages}`, pageW - margin, pageH - 8, { align: 'right' });
  }

  onProgress?.(90);

  const fileName = `${patient.name.replace(/\s+/g, '_')}_${phase}.pdf`;

  if (Capacitor.isNativePlatform()) {
    const { Filesystem, Directory } = await import('@capacitor/filesystem');
    const { Share } = await import('@capacitor/share');
    const base64PDF = pdf.output('datauristring').split(',')[1];
    const saved = await Filesystem.writeFile({ path: fileName, data: base64PDF, directory: Directory.Cache });
    onProgress?.(100);
    await Share.share({
      title: fileName,
      text: `${patient.name} – ${phase === 'PreOp' ? 'Pre-Operative' : 'Post-Operative'} Radiology`,
      url: saved.uri,
      dialogTitle: 'Share via WhatsApp',
    });
  } else {
    pdf.save(fileName);
    onProgress?.(100);
  }
}
